# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: towercontrol.proto for package 'towercontrol'

require 'grpc'
require 'towercontrol_pb'

module Towercontrol
  module Tower
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'towercontrol.Tower'

      rpc :SayAltitude, AltitudeRequest, AltitudeReply
      rpc :SayLandingTrack, LandingTrackRequest, LandingTrackReply
      rpc :SayDepartureTrack, DepartureTrackRequest, DepartureTrackReply
      rpc :SayIpRequest, IpRequest, IpReply
    end

    Stub = Service.rpc_stub_class
  end
end
