# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: towercontrol.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "towercontrol.AltitudeRequest" do
    optional :altitude, :int32, 1
  end
  add_message "towercontrol.AltitudeReply" do
    optional :message, :int32, 1
  end
  add_message "towercontrol.LandingTrackRequest" do
    optional :track, :int32, 1
    optional :altitude, :int32, 2
  end
  add_message "towercontrol.LandingTrackReply" do
    optional :message, :int32, 1
  end
  add_message "towercontrol.DepartureTrackRequest" do
    optional :flightnumber, :string, 1
    optional :destiny, :string, 2
  end
  add_message "towercontrol.DepartureTrackReply" do
    optional :track, :int32, 1
    optional :height, :int32, 2
    optional :ip, :string, 3
  end
  add_message "towercontrol.IpRequest" do
    optional :ip, :string, 1
  end
  add_message "towercontrol.IpReply" do
    optional :altitude, :int32, 1
    optional :ip, :string, 2
  end
end

module Towercontrol
  AltitudeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.AltitudeRequest").msgclass
  AltitudeReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.AltitudeReply").msgclass
  LandingTrackRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.LandingTrackRequest").msgclass
  LandingTrackReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.LandingTrackReply").msgclass
  DepartureTrackRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.DepartureTrackRequest").msgclass
  DepartureTrackReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.DepartureTrackReply").msgclass
  IpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.IpRequest").msgclass
  IpReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.IpReply").msgclass
end
