# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import towercontrol_pb2 as towercontrol__pb2


class TowerStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayAltitude = channel.unary_unary(
        '/towercontrol.Tower/SayAltitude',
        request_serializer=towercontrol__pb2.AltitudeRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.AltitudeReply.FromString,
        )
    self.SayLandingTrack = channel.unary_unary(
        '/towercontrol.Tower/SayLandingTrack',
        request_serializer=towercontrol__pb2.LandingTrackRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.LandingTrackReply.FromString,
        )
    self.SayDepartureTrack = channel.unary_unary(
        '/towercontrol.Tower/SayDepartureTrack',
        request_serializer=towercontrol__pb2.DepartureTrackRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.DepartureTrackReply.FromString,
        )
    self.SayIpRequest = channel.unary_unary(
        '/towercontrol.Tower/SayIpRequest',
        request_serializer=towercontrol__pb2.IpRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.IpReply.FromString,
        )


class TowerServicer(object):
  """The greeting service definition.
  """

  def SayAltitude(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayLandingTrack(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayDepartureTrack(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayIpRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TowerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayAltitude': grpc.unary_unary_rpc_method_handler(
          servicer.SayAltitude,
          request_deserializer=towercontrol__pb2.AltitudeRequest.FromString,
          response_serializer=towercontrol__pb2.AltitudeReply.SerializeToString,
      ),
      'SayLandingTrack': grpc.unary_unary_rpc_method_handler(
          servicer.SayLandingTrack,
          request_deserializer=towercontrol__pb2.LandingTrackRequest.FromString,
          response_serializer=towercontrol__pb2.LandingTrackReply.SerializeToString,
      ),
      'SayDepartureTrack': grpc.unary_unary_rpc_method_handler(
          servicer.SayDepartureTrack,
          request_deserializer=towercontrol__pb2.DepartureTrackRequest.FromString,
          response_serializer=towercontrol__pb2.DepartureTrackReply.SerializeToString,
      ),
      'SayIpRequest': grpc.unary_unary_rpc_method_handler(
          servicer.SayIpRequest,
          request_deserializer=towercontrol__pb2.IpRequest.FromString,
          response_serializer=towercontrol__pb2.IpReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'towercontrol.Tower', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
