# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import towercontrol_pb2 as towercontrol__pb2


class TowerStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayLandingTrack = channel.unary_unary(
        '/towercontrol.Tower/SayLandingTrack',
        request_serializer=towercontrol__pb2.LandingTrackRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.LandingTrackReply.FromString,
        )
    self.SayDepartureTrack = channel.unary_unary(
        '/towercontrol.Tower/SayDepartureTrack',
        request_serializer=towercontrol__pb2.DepartureTrackRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.DepartureTrackReply.FromString,
        )
    self.SayFlights = channel.unary_stream(
        '/towercontrol.Tower/SayFlights',
        request_serializer=towercontrol__pb2.FlightsRequest.SerializeToString,
        response_deserializer=towercontrol__pb2.FlightsResponse.FromString,
        )


class TowerServicer(object):
  """The greeting service definition.
  """

  def SayLandingTrack(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayDepartureTrack(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayFlights(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TowerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayLandingTrack': grpc.unary_unary_rpc_method_handler(
          servicer.SayLandingTrack,
          request_deserializer=towercontrol__pb2.LandingTrackRequest.FromString,
          response_serializer=towercontrol__pb2.LandingTrackReply.SerializeToString,
      ),
      'SayDepartureTrack': grpc.unary_unary_rpc_method_handler(
          servicer.SayDepartureTrack,
          request_deserializer=towercontrol__pb2.DepartureTrackRequest.FromString,
          response_serializer=towercontrol__pb2.DepartureTrackReply.SerializeToString,
      ),
      'SayFlights': grpc.unary_stream_rpc_method_handler(
          servicer.SayFlights,
          request_deserializer=towercontrol__pb2.FlightsRequest.FromString,
          response_serializer=towercontrol__pb2.FlightsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'towercontrol.Tower', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
