# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: towercontrol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='towercontrol.proto',
  package='towercontrol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12towercontrol.proto\x12\x0ctowercontrol\"#\n\x0f\x41ltitudeRequest\x12\x10\n\x08\x61ltitude\x18\x01 \x01(\x05\" \n\rAltitudeReply\x12\x0f\n\x07message\x18\x01 \x01(\x05\"$\n\x13LandingTrackRequest\x12\r\n\x05track\x18\x01 \x01(\x05\"$\n\x11LandingTrackReply\x12\x0f\n\x07message\x18\x01 \x01(\x05\"e\n\x15\x44\x65partureTrackRequest\x12\x0f\n\x07\x61irline\x18\x01 \x01(\t\x12\x14\n\x0c\x66lightnumber\x18\x02 \x01(\t\x12\x14\n\x0cinitialtower\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65stiny\x18\x04 \x01(\t\"4\n\x13\x44\x65partureTrackReply\x12\r\n\x05track\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x17\n\tIpRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"\'\n\x07IpReply\x12\x10\n\x08\x61ltitude\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t2\xce\x02\n\x05Tower\x12K\n\x0bSayAltitude\x12\x1d.towercontrol.AltitudeRequest\x1a\x1b.towercontrol.AltitudeReply\"\x00\x12W\n\x0fSayLandingTrack\x12!.towercontrol.LandingTrackRequest\x1a\x1f.towercontrol.LandingTrackReply\"\x00\x12]\n\x11SayDepartureTrack\x12#.towercontrol.DepartureTrackRequest\x1a!.towercontrol.DepartureTrackReply\"\x00\x12@\n\x0cSayIpRequest\x12\x17.towercontrol.IpRequest\x1a\x15.towercontrol.IpReply\"\x00\x62\x06proto3')
)




_ALTITUDEREQUEST = _descriptor.Descriptor(
  name='AltitudeRequest',
  full_name='towercontrol.AltitudeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='altitude', full_name='towercontrol.AltitudeRequest.altitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=71,
)


_ALTITUDEREPLY = _descriptor.Descriptor(
  name='AltitudeReply',
  full_name='towercontrol.AltitudeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='towercontrol.AltitudeReply.message', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=105,
)


_LANDINGTRACKREQUEST = _descriptor.Descriptor(
  name='LandingTrackRequest',
  full_name='towercontrol.LandingTrackRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track', full_name='towercontrol.LandingTrackRequest.track', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=143,
)


_LANDINGTRACKREPLY = _descriptor.Descriptor(
  name='LandingTrackReply',
  full_name='towercontrol.LandingTrackReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='towercontrol.LandingTrackReply.message', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=181,
)


_DEPARTURETRACKREQUEST = _descriptor.Descriptor(
  name='DepartureTrackRequest',
  full_name='towercontrol.DepartureTrackRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='airline', full_name='towercontrol.DepartureTrackRequest.airline', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flightnumber', full_name='towercontrol.DepartureTrackRequest.flightnumber', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initialtower', full_name='towercontrol.DepartureTrackRequest.initialtower', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destiny', full_name='towercontrol.DepartureTrackRequest.destiny', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=284,
)


_DEPARTURETRACKREPLY = _descriptor.Descriptor(
  name='DepartureTrackReply',
  full_name='towercontrol.DepartureTrackReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track', full_name='towercontrol.DepartureTrackReply.track', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='towercontrol.DepartureTrackReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=338,
)


_IPREQUEST = _descriptor.Descriptor(
  name='IpRequest',
  full_name='towercontrol.IpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='towercontrol.IpRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=363,
)


_IPREPLY = _descriptor.Descriptor(
  name='IpReply',
  full_name='towercontrol.IpReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='altitude', full_name='towercontrol.IpReply.altitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='towercontrol.IpReply.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=404,
)

DESCRIPTOR.message_types_by_name['AltitudeRequest'] = _ALTITUDEREQUEST
DESCRIPTOR.message_types_by_name['AltitudeReply'] = _ALTITUDEREPLY
DESCRIPTOR.message_types_by_name['LandingTrackRequest'] = _LANDINGTRACKREQUEST
DESCRIPTOR.message_types_by_name['LandingTrackReply'] = _LANDINGTRACKREPLY
DESCRIPTOR.message_types_by_name['DepartureTrackRequest'] = _DEPARTURETRACKREQUEST
DESCRIPTOR.message_types_by_name['DepartureTrackReply'] = _DEPARTURETRACKREPLY
DESCRIPTOR.message_types_by_name['IpRequest'] = _IPREQUEST
DESCRIPTOR.message_types_by_name['IpReply'] = _IPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AltitudeRequest = _reflection.GeneratedProtocolMessageType('AltitudeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ALTITUDEREQUEST,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.AltitudeRequest)
  ))
_sym_db.RegisterMessage(AltitudeRequest)

AltitudeReply = _reflection.GeneratedProtocolMessageType('AltitudeReply', (_message.Message,), dict(
  DESCRIPTOR = _ALTITUDEREPLY,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.AltitudeReply)
  ))
_sym_db.RegisterMessage(AltitudeReply)

LandingTrackRequest = _reflection.GeneratedProtocolMessageType('LandingTrackRequest', (_message.Message,), dict(
  DESCRIPTOR = _LANDINGTRACKREQUEST,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.LandingTrackRequest)
  ))
_sym_db.RegisterMessage(LandingTrackRequest)

LandingTrackReply = _reflection.GeneratedProtocolMessageType('LandingTrackReply', (_message.Message,), dict(
  DESCRIPTOR = _LANDINGTRACKREPLY,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.LandingTrackReply)
  ))
_sym_db.RegisterMessage(LandingTrackReply)

DepartureTrackRequest = _reflection.GeneratedProtocolMessageType('DepartureTrackRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPARTURETRACKREQUEST,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.DepartureTrackRequest)
  ))
_sym_db.RegisterMessage(DepartureTrackRequest)

DepartureTrackReply = _reflection.GeneratedProtocolMessageType('DepartureTrackReply', (_message.Message,), dict(
  DESCRIPTOR = _DEPARTURETRACKREPLY,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.DepartureTrackReply)
  ))
_sym_db.RegisterMessage(DepartureTrackReply)

IpRequest = _reflection.GeneratedProtocolMessageType('IpRequest', (_message.Message,), dict(
  DESCRIPTOR = _IPREQUEST,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.IpRequest)
  ))
_sym_db.RegisterMessage(IpRequest)

IpReply = _reflection.GeneratedProtocolMessageType('IpReply', (_message.Message,), dict(
  DESCRIPTOR = _IPREPLY,
  __module__ = 'towercontrol_pb2'
  # @@protoc_insertion_point(class_scope:towercontrol.IpReply)
  ))
_sym_db.RegisterMessage(IpReply)



_TOWER = _descriptor.ServiceDescriptor(
  name='Tower',
  full_name='towercontrol.Tower',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=407,
  serialized_end=741,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayAltitude',
    full_name='towercontrol.Tower.SayAltitude',
    index=0,
    containing_service=None,
    input_type=_ALTITUDEREQUEST,
    output_type=_ALTITUDEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayLandingTrack',
    full_name='towercontrol.Tower.SayLandingTrack',
    index=1,
    containing_service=None,
    input_type=_LANDINGTRACKREQUEST,
    output_type=_LANDINGTRACKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayDepartureTrack',
    full_name='towercontrol.Tower.SayDepartureTrack',
    index=2,
    containing_service=None,
    input_type=_DEPARTURETRACKREQUEST,
    output_type=_DEPARTURETRACKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayIpRequest',
    full_name='towercontrol.Tower.SayIpRequest',
    index=3,
    containing_service=None,
    input_type=_IPREQUEST,
    output_type=_IPREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOWER)

DESCRIPTOR.services_by_name['Tower'] = _TOWER

# @@protoc_insertion_point(module_scope)
