# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: towercontrol.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "towercontrol.AltitudeRequest" do
    optional :altitude, :int32, 1
  end
  add_message "towercontrol.AltitudeReply" do
    optional :message, :int32, 1
  end
  add_message "towercontrol.LandingTrackRequest" do
    optional :track, :int32, 1
    optional :altitude, :int32, 2
    optional :flightnumber, :string, 3
    optional :destiny, :string, 4
  end
  add_message "towercontrol.LandingTrackReply" do
    optional :message, :int32, 1
    optional :pos, :int32, 2
    optional :altitude, :int32, 3
  end
  add_message "towercontrol.DepartureTrackRequest" do
    optional :flightnumber, :string, 1
    optional :destiny, :string, 2
  end
  add_message "towercontrol.DepartureTrackReply" do
    optional :track, :int32, 1
    optional :height, :int32, 2
    optional :ip, :string, 3
    optional :port, :string, 4
    optional :pos, :int32, 5
  end
  add_message "towercontrol.FlightsRequest" do
    optional :message, :int32, 1
  end
  add_message "towercontrol.FlightsResponse" do
    optional :type, :string, 1
    optional :airport, :string, 2
    optional :flight, :string, 3
    optional :destiny, :string, 4
    optional :track, :int32, 5
  end
end

module Towercontrol
  AltitudeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.AltitudeRequest").msgclass
  AltitudeReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.AltitudeReply").msgclass
  LandingTrackRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.LandingTrackRequest").msgclass
  LandingTrackReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.LandingTrackReply").msgclass
  DepartureTrackRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.DepartureTrackRequest").msgclass
  DepartureTrackReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.DepartureTrackReply").msgclass
  FlightsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.FlightsRequest").msgclass
  FlightsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("towercontrol.FlightsResponse").msgclass
end
